package net.minecraft.client.model.geom;

import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import net.minecraft.client.model.ArmorStandArmorModel;
import net.minecraft.client.model.ArmorStandModel;
import net.minecraft.client.model.AxolotlModel;
import net.minecraft.client.model.BatModel;
import net.minecraft.client.model.BeeModel;
import net.minecraft.client.model.BlazeModel;
import net.minecraft.client.model.BoatModel;
import net.minecraft.client.model.BookModel;
import net.minecraft.client.model.ChestedHorseModel;
import net.minecraft.client.model.ChickenModel;
import net.minecraft.client.model.CodModel;
import net.minecraft.client.model.CowModel;
import net.minecraft.client.model.CreeperModel;
import net.minecraft.client.model.DolphinModel;
import net.minecraft.client.model.DrownedModel;
import net.minecraft.client.model.ElytraModel;
import net.minecraft.client.model.EndermanModel;
import net.minecraft.client.model.EndermiteModel;
import net.minecraft.client.model.EvokerFangsModel;
import net.minecraft.client.model.FoxModel;
import net.minecraft.client.model.GhastModel;
import net.minecraft.client.model.GoatModel;
import net.minecraft.client.model.GuardianModel;
import net.minecraft.client.model.HoglinModel;
import net.minecraft.client.model.HorseModel;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.IllagerModel;
import net.minecraft.client.model.IronGolemModel;
import net.minecraft.client.model.LavaSlimeModel;
import net.minecraft.client.model.LeashKnotModel;
import net.minecraft.client.model.LlamaModel;
import net.minecraft.client.model.LlamaSpitModel;
import net.minecraft.client.model.MinecartModel;
import net.minecraft.client.model.OcelotModel;
import net.minecraft.client.model.PandaModel;
import net.minecraft.client.model.ParrotModel;
import net.minecraft.client.model.PhantomModel;
import net.minecraft.client.model.PigModel;
import net.minecraft.client.model.PiglinModel;
import net.minecraft.client.model.PlayerModel;
import net.minecraft.client.model.PolarBearModel;
import net.minecraft.client.model.PufferfishBigModel;
import net.minecraft.client.model.PufferfishMidModel;
import net.minecraft.client.model.PufferfishSmallModel;
import net.minecraft.client.model.RabbitModel;
import net.minecraft.client.model.RavagerModel;
import net.minecraft.client.model.SalmonModel;
import net.minecraft.client.model.SheepFurModel;
import net.minecraft.client.model.SheepModel;
import net.minecraft.client.model.ShieldModel;
import net.minecraft.client.model.ShulkerBulletModel;
import net.minecraft.client.model.ShulkerModel;
import net.minecraft.client.model.SilverfishModel;
import net.minecraft.client.model.SkeletonModel;
import net.minecraft.client.model.SkullModel;
import net.minecraft.client.model.SlimeModel;
import net.minecraft.client.model.SnowGolemModel;
import net.minecraft.client.model.SpiderModel;
import net.minecraft.client.model.SquidModel;
import net.minecraft.client.model.StriderModel;
import net.minecraft.client.model.TridentModel;
import net.minecraft.client.model.TropicalFishModelA;
import net.minecraft.client.model.TropicalFishModelB;
import net.minecraft.client.model.TurtleModel;
import net.minecraft.client.model.VexModel;
import net.minecraft.client.model.VillagerModel;
import net.minecraft.client.model.WitchModel;
import net.minecraft.client.model.WitherBossModel;
import net.minecraft.client.model.WolfModel;
import net.minecraft.client.model.ZombieVillagerModel;
import net.minecraft.client.model.dragon.DragonHeadModel;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.renderer.blockentity.BannerRenderer;
import net.minecraft.client.renderer.blockentity.BedRenderer;
import net.minecraft.client.renderer.blockentity.BellRenderer;
import net.minecraft.client.renderer.blockentity.ChestRenderer;
import net.minecraft.client.renderer.blockentity.ConduitRenderer;
import net.minecraft.client.renderer.blockentity.SignRenderer;
import net.minecraft.client.renderer.entity.EndCrystalRenderer;
import net.minecraft.client.renderer.entity.EnderDragonRenderer;
import net.minecraft.client.renderer.entity.WitherSkullRenderer;
import net.minecraft.client.renderer.entity.layers.SpinAttackEffectLayer;
import net.minecraft.world.entity.vehicle.Boat;
import net.minecraft.world.level.block.state.properties.WoodType;

public class LayerDefinitions {
   private static final CubeDeformation FISH_PATTERN_DEFORMATION = new CubeDeformation(0.008F);
   private static final CubeDeformation OUTER_ARMOR_DEFORMATION = new CubeDeformation(1.0F);
   private static final CubeDeformation INNER_ARMOR_DEFORMATION = new CubeDeformation(0.5F);

   public static Map<ModelLayerLocation, LayerDefinition> createRoots() {
      Builder<ModelLayerLocation, LayerDefinition> â˜ƒ = ImmutableMap.builder();
      LayerDefinition â˜ƒx = LayerDefinition.create(HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F), 64, 64);
      LayerDefinition â˜ƒxx = LayerDefinition.create(HumanoidModel.createMesh(OUTER_ARMOR_DEFORMATION, 0.0F), 64, 32);
      LayerDefinition â˜ƒxxx = LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(1.02F), 0.0F), 64, 32);
      LayerDefinition â˜ƒxxxx = LayerDefinition.create(HumanoidModel.createMesh(INNER_ARMOR_DEFORMATION, 0.0F), 64, 32);
      LayerDefinition â˜ƒxxxxx = MinecartModel.createBodyLayer();
      LayerDefinition â˜ƒxxxxxx = SkullModel.createMobHeadLayer();
      LayerDefinition â˜ƒxxxxxxx = LayerDefinition.create(HorseModel.createBodyMesh(CubeDeformation.NONE), 64, 64);
      LayerDefinition â˜ƒxxxxxxxx = IllagerModel.createBodyLayer();
      LayerDefinition â˜ƒxxxxxxxxx = CowModel.createBodyLayer();
      LayerDefinition â˜ƒxxxxxxxxxx = LayerDefinition.create(OcelotModel.createBodyMesh(CubeDeformation.NONE), 64, 32);
      LayerDefinition â˜ƒxxxxxxxxxxx = LayerDefinition.create(PiglinModel.createMesh(CubeDeformation.NONE), 64, 64);
      LayerDefinition â˜ƒxxxxxxxxxxxx = SkullModel.createHumanoidHeadLayer();
      LayerDefinition â˜ƒxxxxxxxxxxxxx = LlamaModel.createBodyLayer(CubeDeformation.NONE);
      LayerDefinition â˜ƒxxxxxxxxxxxxxx = StriderModel.createBodyLayer();
      LayerDefinition â˜ƒxxxxxxxxxxxxxxx = HoglinModel.createBodyLayer();
      LayerDefinition â˜ƒxxxxxxxxxxxxxxxx = SkeletonModel.createBodyLayer();
      LayerDefinition â˜ƒxxxxxxxxxxxxxxxxx = LayerDefinition.create(VillagerModel.createBodyModel(), 64, 64);
      LayerDefinition â˜ƒxxxxxxxxxxxxxxxxxx = SpiderModel.createSpiderBodyLayer();
      â˜ƒ.put(ModelLayers.ARMOR_STAND, ArmorStandModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.ARMOR_STAND_INNER_ARMOR, ArmorStandArmorModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
      â˜ƒ.put(ModelLayers.ARMOR_STAND_OUTER_ARMOR, ArmorStandArmorModel.createBodyLayer(OUTER_ARMOR_DEFORMATION));
      â˜ƒ.put(ModelLayers.AXOLOTL, AxolotlModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.BANNER, BannerRenderer.createBodyLayer());
      â˜ƒ.put(ModelLayers.BAT, BatModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.BED_FOOT, BedRenderer.createFootLayer());
      â˜ƒ.put(ModelLayers.BED_HEAD, BedRenderer.createHeadLayer());
      â˜ƒ.put(ModelLayers.BEE, BeeModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.BELL, BellRenderer.createBodyLayer());
      â˜ƒ.put(ModelLayers.BLAZE, BlazeModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.BOOK, BookModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.CAT, â˜ƒxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.CAT_COLLAR, LayerDefinition.create(OcelotModel.createBodyMesh(new CubeDeformation(0.01F)), 64, 32));
      â˜ƒ.put(ModelLayers.CAVE_SPIDER, â˜ƒxxxxxxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.CHEST, ChestRenderer.createSingleBodyLayer());
      â˜ƒ.put(ModelLayers.DOUBLE_CHEST_LEFT, ChestRenderer.createDoubleBodyLeftLayer());
      â˜ƒ.put(ModelLayers.DOUBLE_CHEST_RIGHT, ChestRenderer.createDoubleBodyRightLayer());
      â˜ƒ.put(ModelLayers.CHEST_MINECART, â˜ƒxxxxx);
      â˜ƒ.put(ModelLayers.CHICKEN, ChickenModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.COD, CodModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.COMMAND_BLOCK_MINECART, â˜ƒxxxxx);
      â˜ƒ.put(ModelLayers.CONDUIT_EYE, ConduitRenderer.createEyeLayer());
      â˜ƒ.put(ModelLayers.CONDUIT_WIND, ConduitRenderer.createWindLayer());
      â˜ƒ.put(ModelLayers.CONDUIT_SHELL, ConduitRenderer.createShellLayer());
      â˜ƒ.put(ModelLayers.CONDUIT_CAGE, ConduitRenderer.createCageLayer());
      â˜ƒ.put(ModelLayers.COW, â˜ƒxxxxxxxxx);
      â˜ƒ.put(ModelLayers.CREEPER, CreeperModel.createBodyLayer(CubeDeformation.NONE));
      â˜ƒ.put(ModelLayers.CREEPER_ARMOR, CreeperModel.createBodyLayer(new CubeDeformation(2.0F)));
      â˜ƒ.put(ModelLayers.CREEPER_HEAD, â˜ƒxxxxxx);
      â˜ƒ.put(ModelLayers.DOLPHIN, DolphinModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.DONKEY, ChestedHorseModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.DRAGON_SKULL, DragonHeadModel.createHeadLayer());
      â˜ƒ.put(ModelLayers.DROWNED, DrownedModel.createBodyLayer(CubeDeformation.NONE));
      â˜ƒ.put(ModelLayers.DROWNED_INNER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.DROWNED_OUTER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.DROWNED_OUTER_LAYER, DrownedModel.createBodyLayer(new CubeDeformation(0.25F)));
      â˜ƒ.put(ModelLayers.ELDER_GUARDIAN, GuardianModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.ELYTRA, ElytraModel.createLayer());
      â˜ƒ.put(ModelLayers.ENDERMAN, EndermanModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.ENDERMITE, EndermiteModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.ENDER_DRAGON, EnderDragonRenderer.createBodyLayer());
      â˜ƒ.put(ModelLayers.END_CRYSTAL, EndCrystalRenderer.createBodyLayer());
      â˜ƒ.put(ModelLayers.EVOKER, â˜ƒxxxxxxxx);
      â˜ƒ.put(ModelLayers.EVOKER_FANGS, EvokerFangsModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.FOX, FoxModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.FURNACE_MINECART, â˜ƒxxxxx);
      â˜ƒ.put(ModelLayers.GHAST, GhastModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.GIANT, â˜ƒx);
      â˜ƒ.put(ModelLayers.GIANT_INNER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.GIANT_OUTER_ARMOR, â˜ƒxx);
      â˜ƒ.put(ModelLayers.GLOW_SQUID, SquidModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.GOAT, GoatModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.GUARDIAN, GuardianModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.HOGLIN, â˜ƒxxxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.HOPPER_MINECART, â˜ƒxxxxx);
      â˜ƒ.put(ModelLayers.HORSE, â˜ƒxxxxxxx);
      â˜ƒ.put(ModelLayers.HORSE_ARMOR, LayerDefinition.create(HorseModel.createBodyMesh(new CubeDeformation(0.1F)), 64, 64));
      â˜ƒ.put(ModelLayers.HUSK, â˜ƒx);
      â˜ƒ.put(ModelLayers.HUSK_INNER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.HUSK_OUTER_ARMOR, â˜ƒxx);
      â˜ƒ.put(ModelLayers.ILLUSIONER, â˜ƒxxxxxxxx);
      â˜ƒ.put(ModelLayers.IRON_GOLEM, IronGolemModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.LEASH_KNOT, LeashKnotModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.LLAMA, â˜ƒxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.LLAMA_DECOR, LlamaModel.createBodyLayer(new CubeDeformation(0.5F)));
      â˜ƒ.put(ModelLayers.LLAMA_SPIT, LlamaSpitModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.MAGMA_CUBE, LavaSlimeModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.MINECART, â˜ƒxxxxx);
      â˜ƒ.put(ModelLayers.MOOSHROOM, â˜ƒxxxxxxxxx);
      â˜ƒ.put(ModelLayers.MULE, ChestedHorseModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.OCELOT, â˜ƒxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.PANDA, PandaModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.PARROT, ParrotModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.PHANTOM, PhantomModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.PIG, PigModel.createBodyLayer(CubeDeformation.NONE));
      â˜ƒ.put(ModelLayers.PIG_SADDLE, PigModel.createBodyLayer(new CubeDeformation(0.5F)));
      â˜ƒ.put(ModelLayers.PIGLIN, â˜ƒxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.PIGLIN_INNER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.PIGLIN_OUTER_ARMOR, â˜ƒxxx);
      â˜ƒ.put(ModelLayers.PIGLIN_BRUTE, â˜ƒxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.PIGLIN_BRUTE_INNER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.PIGLIN_BRUTE_OUTER_ARMOR, â˜ƒxxx);
      â˜ƒ.put(ModelLayers.PILLAGER, â˜ƒxxxxxxxx);
      â˜ƒ.put(ModelLayers.PLAYER, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, false), 64, 64));
      â˜ƒ.put(ModelLayers.PLAYER_HEAD, â˜ƒxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.PLAYER_INNER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.PLAYER_OUTER_ARMOR, â˜ƒxx);
      â˜ƒ.put(ModelLayers.PLAYER_SLIM, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, true), 64, 64));
      â˜ƒ.put(ModelLayers.PLAYER_SLIM_INNER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.PLAYER_SLIM_OUTER_ARMOR, â˜ƒxx);
      â˜ƒ.put(ModelLayers.PLAYER_SPIN_ATTACK, SpinAttackEffectLayer.createLayer());
      â˜ƒ.put(ModelLayers.POLAR_BEAR, PolarBearModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.PUFFERFISH_BIG, PufferfishBigModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.PUFFERFISH_MEDIUM, PufferfishMidModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.PUFFERFISH_SMALL, PufferfishSmallModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.RABBIT, RabbitModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.RAVAGER, RavagerModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.SALMON, SalmonModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.SHEEP, SheepModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.SHEEP_FUR, SheepFurModel.createFurLayer());
      â˜ƒ.put(ModelLayers.SHIELD, ShieldModel.createLayer());
      â˜ƒ.put(ModelLayers.SHULKER, ShulkerModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.SHULKER_BULLET, ShulkerBulletModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.SILVERFISH, SilverfishModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.SKELETON, â˜ƒxxxxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.SKELETON_INNER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.SKELETON_OUTER_ARMOR, â˜ƒxx);
      â˜ƒ.put(ModelLayers.SKELETON_HORSE, â˜ƒxxxxxxx);
      â˜ƒ.put(ModelLayers.SKELETON_SKULL, â˜ƒxxxxxx);
      â˜ƒ.put(ModelLayers.SLIME, SlimeModel.createInnerBodyLayer());
      â˜ƒ.put(ModelLayers.SLIME_OUTER, SlimeModel.createOuterBodyLayer());
      â˜ƒ.put(ModelLayers.SNOW_GOLEM, SnowGolemModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.SPAWNER_MINECART, â˜ƒxxxxx);
      â˜ƒ.put(ModelLayers.SPIDER, â˜ƒxxxxxxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.SQUID, SquidModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.STRAY, â˜ƒxxxxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.STRAY_INNER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.STRAY_OUTER_ARMOR, â˜ƒxx);
      â˜ƒ.put(ModelLayers.STRAY_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25F), 0.0F), 64, 32));
      â˜ƒ.put(ModelLayers.STRIDER, â˜ƒxxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.STRIDER_SADDLE, â˜ƒxxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.TNT_MINECART, â˜ƒxxxxx);
      â˜ƒ.put(ModelLayers.TRADER_LLAMA, â˜ƒxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.TRIDENT, TridentModel.createLayer());
      â˜ƒ.put(ModelLayers.TROPICAL_FISH_LARGE, TropicalFishModelB.createBodyLayer(CubeDeformation.NONE));
      â˜ƒ.put(ModelLayers.TROPICAL_FISH_LARGE_PATTERN, TropicalFishModelB.createBodyLayer(FISH_PATTERN_DEFORMATION));
      â˜ƒ.put(ModelLayers.TROPICAL_FISH_SMALL, TropicalFishModelA.createBodyLayer(CubeDeformation.NONE));
      â˜ƒ.put(ModelLayers.TROPICAL_FISH_SMALL_PATTERN, TropicalFishModelA.createBodyLayer(FISH_PATTERN_DEFORMATION));
      â˜ƒ.put(ModelLayers.TURTLE, TurtleModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.VEX, VexModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.VILLAGER, â˜ƒxxxxxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.VINDICATOR, â˜ƒxxxxxxxx);
      â˜ƒ.put(ModelLayers.WANDERING_TRADER, â˜ƒxxxxxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.WITCH, WitchModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.WITHER, WitherBossModel.createBodyLayer(CubeDeformation.NONE));
      â˜ƒ.put(ModelLayers.WITHER_ARMOR, WitherBossModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
      â˜ƒ.put(ModelLayers.WITHER_SKULL, WitherSkullRenderer.createSkullLayer());
      â˜ƒ.put(ModelLayers.WITHER_SKELETON, â˜ƒxxxxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.WITHER_SKELETON_INNER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.WITHER_SKELETON_OUTER_ARMOR, â˜ƒxx);
      â˜ƒ.put(ModelLayers.WITHER_SKELETON_SKULL, â˜ƒxxxxxx);
      â˜ƒ.put(ModelLayers.WOLF, WolfModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.ZOGLIN, â˜ƒxxxxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.ZOMBIE, â˜ƒx);
      â˜ƒ.put(ModelLayers.ZOMBIE_INNER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.ZOMBIE_OUTER_ARMOR, â˜ƒxx);
      â˜ƒ.put(ModelLayers.ZOMBIE_HEAD, â˜ƒxxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.ZOMBIE_HORSE, â˜ƒxxxxxxx);
      â˜ƒ.put(ModelLayers.ZOMBIE_VILLAGER, ZombieVillagerModel.createBodyLayer());
      â˜ƒ.put(ModelLayers.ZOMBIE_VILLAGER_INNER_ARMOR, ZombieVillagerModel.createArmorLayer(INNER_ARMOR_DEFORMATION));
      â˜ƒ.put(ModelLayers.ZOMBIE_VILLAGER_OUTER_ARMOR, ZombieVillagerModel.createArmorLayer(OUTER_ARMOR_DEFORMATION));
      â˜ƒ.put(ModelLayers.ZOMBIFIED_PIGLIN, â˜ƒxxxxxxxxxxx);
      â˜ƒ.put(ModelLayers.ZOMBIFIED_PIGLIN_INNER_ARMOR, â˜ƒxxxx);
      â˜ƒ.put(ModelLayers.ZOMBIFIED_PIGLIN_OUTER_ARMOR, â˜ƒxxx);
      LayerDefinition â˜ƒxxxxxxxxxxxxxxxxxxx = BoatModel.createBodyModel();

      for(Boat.Type â˜ƒxxxxxxxxxxxxxxxxxxxx : Boat.Type.values()) {
         â˜ƒ.put(ModelLayers.createBoatModelName(â˜ƒxxxxxxxxxxxxxxxxxxxx), â˜ƒxxxxxxxxxxxxxxxxxxx);
      }

      LayerDefinition â˜ƒxxxxxxxxxxxxxxxxxxxx = SignRenderer.createSignLayer();
      WoodType.values().forEach(var2x -> â˜ƒ.put(ModelLayers.createSignModelName(var2x), â˜ƒ));
      ImmutableMap<ModelLayerLocation, LayerDefinition> â˜ƒxxxxxxxxxxxxxxxxxxxxx = â˜ƒ.build();
      List<ModelLayerLocation> â˜ƒxxxxxxxxxxxxxxxxxxxxxx = (List)ModelLayers.getKnownLocations()
         .filter(var1x -> !â˜ƒ.containsKey(var1x))
         .collect(Collectors.toList());
      if (!â˜ƒxxxxxxxxxxxxxxxxxxxxxx.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + â˜ƒxxxxxxxxxxxxxxxxxxxxxx);
      } else {
         return â˜ƒxxxxxxxxxxxxxxxxxxxxx;
      }
   }
}
