#Minecraft server properties
#Wed Sep 09 11:20:56 JST 2026
level-name=smoke-world
allow-nether=true
view-distance=10
spawn-monsters=true
online-mode=false
spawn-animals=true
max-players=20
server-ip=127.0.0.1
pvp=true
level-seed=8675309
server-port=57245
allow-flight=false
white-list=false
